# Generated by Django 2.1.2 on 2018-11-04 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrelatednotes',
            name='executor',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskrelatednotes',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='currencycirculation',
            name='task',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='currencycirculation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
